administration/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('profile', views.profile, name='a_profile'),
    path('register', views.a_register, name='a_register'),
    path('dashboard', views.dashboard, name='a_dashboard'),
    path('all_cases', views.all_cases, name='a_cases'),
    path('donors', views.donors, name='a_donors'),
    path('users', views.users_list, name='a_users'),
    path('subadmin/<str:pk>', views.add_subadmin, name='a_add_sub'),
    path('rem_subadmin/<str:pk>', views.rem_subadmin, name='a_rem_sub'),
    path('cases/<str:uuid>', views.case_details, name='a_case_details'),

    path('blog', views.blog, name='a_blog'),
    path('events', views.events, name='a_events'),
    path('media', views.media, name='a_media'),
    path('volunteer/', views.volunteer, name='a_volunteer'),

    path('gallery', views.gallery, name='a_gallery'),
    path('gallery/del/<str:pk>', views.del_img_set, name='a_gallery_del'),
    path('gallery/add/<str:pk>', views.add_new_images, name='a_new_img'),
    path('gallery/del/img/<str:pk>', views.del_img, name='a_del_img'),

    path('add_case', views.add_case, name='a_add'),
    path('edit_case/<str:uuid>', views.edit_case, name='a_edit'),
    path('approve_case/<str:uuid>', views.approve_case, name='a_approve'),
    path('reject_case/<str:uuid>', views.reject_case, name='a_reject'),
    path('delete_case/<str:uuid>', views.delete_case, name='a_delete'),
    path('close_case/<str:uuid>', views.close_case, name='a_close'),
]

blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('blog', views.blog, name='blog'),
    path('blog/details/<str:uuid>', views.details, name='blog_post'),
    path('blog/create', views.create_blog, name='create_blog'),
    path('blog/edit/<str:uuid>', views.edit_blog, name='edit_blog'),
    path('blog/delete/<str:uuid>', views.delete_blog, name='del_blog'),


    path('edit_comment/<str:pk>', views.edit_comment, name='edit_comment'),
    path('delete_comment/<str:pk>', views.delete_comment, name='delete_comment'),
]

events/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('events', views.events, name='events'),
    path('events/details/<str:pk>', views.event_details, name='event_details'),
    path('events/create', views.add_event, name='create_event'),
    path('events/edit/<str:pk>', views.edit_event, name='edit_event'),
    path('events/delete/<str:pk>', views.del_event, name='del_event'),

    path('become_volunteer', views.volunteer, name='volunteer'),
    path('form_submitted', views.volunteer_successful, name='v_successful'),
    path('vol_accepted/<str:pk>', views.volunteer_accept, name='v_accept'),
    path('vol_rejected/<str:pk>', views.volunteer_reject, name='v_reject'),

    path('vol_del/<str:pk>', views.vol_del, name='v_del'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('public.urls')),
    path('', include('projects.urls')),
    path('', include('account.urls')),
    path('', include('blog.urls')),
    path('', include('events.urls')),
    path('', include('spotlight.urls')),
    path('a/', include('administration.urls')),
    path('api/account/', include('account.api.urls')),
    path('api/projects/', include('projects.api.urls')),
    path('api/blog/', include('blog.api.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

handler404 = 'public.views.pg_not_found_error'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administration/models.py
from django.db import models

# Create your models here.

blog/models.py
import uuid as uuid
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from account.models import AccountUser
import uuid


class BlogPost(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, null=True)
    thumbnail = models.ImageField(null=True, blank=True)
    title = models.CharField(max_length=250, null=True)
    overview = RichTextUploadingField(null=True)
    posted_on = models.DateTimeField(auto_now_add=True, null=True)
    posted_by = models.ForeignKey(AccountUser, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    class Meta:
        ordering = ['-posted_on']

    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, null=True)
    comment = models.CharField(max_length=500, null=True)
    posted_by = models.ForeignKey(AccountUser, null=True, on_delete=models.CASCADE)
    posted_on = models.DateTimeField(auto_now_add=True, null=True)

events/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Event(models.Model):
    thumbnail = models.ImageField(null=True, blank=True)
    title = models.CharField(max_length=250, null=True)
    description = RichTextField(null=True)
    start_date = models.DateTimeField(auto_now_add=False, null=True)
    end_date = models.DateTimeField(auto_now_add=False, null=True)
    location = models.CharField(max_length=250, null=True)


class Volunteer(models.Model):
    GENDER = (
        ('Male', 'Male'),
        ('Female', 'Female')
    )
    CONTRIBUTE = (
        ('From Home', 'Volunteer From Home'),
        ('Outdoor', 'Volunteer Outdoor')
    )
    STATUS = (
        ('Accepted', 'Accepted'),
        ('Pending', 'Pending'),
        ('Rejected', 'Rejected')
    )
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    gender = models.CharField(max_length=200, null=True, choices=GENDER)
    date_of_birth = models.DateField(auto_now_add=False, null=True)
    education_background = models.CharField(max_length=200, null=True)
    address = models.CharField(max_length=200, null=True)
    occupation = models.CharField(max_length=200, null=True)
    way_of_contribution = models.CharField(max_length=200, null=True, choices=CONTRIBUTE)
    hours_per_day = models.CharField(max_length=20, null=True)
    application_date = models.DateTimeField(auto_now_add=True, blank=True)
    status = models.CharField(max_length=50, null=True, default='Pending')

projects/models.py
import uuid as uuid
from django.db import models
from account.models import AccountUser, UserProfile
from model_utils.managers import InheritanceManager
from ckeditor.fields import RichTextField
from datetime import datetime


class Case(models.Model):
    STATUS = (
        ('Green', 'Green'),
        ('Orange', 'Orange'),
        ('Red', 'Red'),
        ('Closed', 'Closed'),
    )
    thumbnail = models.ImageField(null=True, blank=True, default='static/assets/img/default-thumbnail.jpg')
    title = models.CharField(max_length=100, null=True, blank=True)
    description = RichTextField(null=True, blank=True)
    created_by = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True, blank=True)
    uuid = models.UUIDField(default=uuid.uuid4, null=True)
    type = models.CharField(max_length=20, null=True, blank=True)
    requested_amount = models.FloatField(null=True, blank=True, default=0.0)
    total_collected = models.FloatField(null=True, blank=True, default=0.0)
    total_online = models.FloatField(null=True, blank=True, default=0.0)
    priority = models.IntegerField(null=True, blank=True, default=0)
    date_of_initiation = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    other_financial_assistance = models.CharField(max_length=100, null=True, blank=True)
    verified_by = models.ForeignKey(AccountUser, null=True, blank=True, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, null=True, choices=STATUS, default='Orange')

    objects = InheritanceManager()

    def __str__(self):
        return self.title

    def get_proper_child(self):
        return getattr(self, f'{self.type.lower()}case')

    @property
    def proper_total(self):
        online = self.total_online or 0.0
        offline = self.total_collected or 0.0
        return online + offline

    @property
    def has_finished(self):
        total = self.proper_total
        if total >= float(self.requested_amount or 0.0):
            self.status = 'Closed'
            self.save()
            return True
        else:
            return False

    @property
    def custom_id(self):
        year = self.date_of_initiation.year
        types = {
            'General': 'Gen', 'Educational': 'EDU', 'Medical': 'MEDL', 'Medicine': 'MEDN',
            'Provisional': "PRO"
        }
        return f'{year}{types[str(self.type)]}{self.pk}'


class EducationalCase(Case):
    # fields for education (death cert for orphan)category
    is_orphan = models.BooleanField(null=True, blank=True)
    death_cert = models.FileField(null=True, blank=True)
    guardian = models.CharField(max_length=200, null=True, blank=True)
    name_of_school = models.CharField(max_length=100, null=True, blank=True)
    location_of_school = models.CharField(max_length=200, null=True, blank=True)
    grade = models.CharField(max_length=10, null=True, blank=True)
    fee_structure = models.FileField(null=True, blank=True)


class GeneralCase(Case):
    # fields for general category
    nature_of_aid = models.CharField(max_length=200, null=True, blank=True)
    estimated_cost_cert = models.FileField(null=True, blank=True)


class MedicalCase(Case):
    # fields for medical category (and for 3 fields of medicine)
    nature_of_disease = models.CharField(max_length=50, null=True, blank=True)
    admitted_in_hospital = models.BooleanField(null=True, blank=True)
    name_of_hospital = models.CharField(max_length=50, null=True, blank=True)
    estimation_letter = models.FileField(null=True, blank=True)


class MedicineCase(Case):
    # medicine
    nature_of_disease = models.CharField(max_length=50, null=True, blank=True)
    name_of_hospital = models.CharField(max_length=50, null=True, blank=True)
    estimation_letter = models.FileField(null=True, blank=True)
    name_of_medicine = models.CharField(max_length=100, null=True, blank=True)


class ProvisionalCase(Case):
    # fields for provisional case
    MARITAL_STATUS = (
        ('Unmarried', 'Unmarried'),
        ('Married', 'Married'),
        ('Single', 'Single'),
        ('Widow', 'Widow'),
    )
    death_cert = models.FileField(null=True, blank=True)
    marital_status = models.CharField(max_length=20, null=True, blank=True, choices=MARITAL_STATUS)


class ProjectDonation(models.Model):
    GENDER = (
        ('Male', 'Male'),
        ('Female', 'Female')
    )
    donor = models.ForeignKey(AccountUser, null=True, on_delete=models.CASCADE, blank=True)
    full_name = models.CharField(max_length=255, null=True)
    email = models.CharField(max_length=255, null=True)
    phone_number = models.CharField(max_length=55, null=True)
    address = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=55, null=True)
    state = models.CharField(max_length=75, null=True)
    country = models.CharField(max_length=55, null=True)
    pan = models.CharField(max_length=100, null=True)
    date_of_birth = models.DateField(auto_now_add=False, null=True)
    gender = models.CharField(max_length=20, null=True, choices=GENDER)
    transaction_id = models.CharField(max_length=100, null=True)
    date = models.DateTimeField(auto_now_add=True)
    amount = models.FloatField(null=True)
    category = models.CharField(max_length=100, null=True, blank=True)
    case = models.ForeignKey(Case, null=True, on_delete=models.SET_NULL, blank=True)


class FamilyMembers(models.Model):
    name = models.CharField(max_length=30, null=True)
    age = models.CharField(max_length=4, null=True)
    monthly_income = models.IntegerField(null=True)
    relation = models.CharField(max_length=50, null=True)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True)
    verified = models.BooleanField(default=False, null=True)


class ClosedDocs(models.Model):
    case = models.ForeignKey(Case, null=True, blank=True, on_delete=models.CASCADE)
    doc = models.FileField(null=True, blank=True)


class ExtraDocs(models.Model):
    case = models.ForeignKey(Case, null=True, blank=True, on_delete=models.CASCADE)
    doc = models.FileField(null=True, blank=True)


class ExtraImages(models.Model):
    case = models.ForeignKey(Case, null=True, blank=True, on_delete=models.CASCADE)
    img = models.ImageField(null=True, blank=True)

spotlight/models.py
from django.db import models


class MediaSpotlight(models.Model):
    title = models.CharField(max_length=250, null=True)
    link = models.CharField(max_length=250, null=True, blank=True)
    date_published = models.DateTimeField(auto_now_add=False, null=True)
    description = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.title


class SpotlightImages(models.Model):
    media = models.ForeignKey(MediaSpotlight, null=True, on_delete=models.CASCADE)
    image = models.ImageField(null=True)

blog/forms.py
from django import forms
from .models import Comment, BlogPost


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'overview', 'thumbnail']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Post Title', 'required': ''}),
            'overview': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write here...', 'required': ''}),
            'thumbnail': forms.FileInput(attrs={'class': 'form-control'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        widgets = {
            'comment': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write your comment here...', 'required': ''}),
        }

blog/api/views.py
from rest_framework.response import Response
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from .serializers import BlogPostSerializer, CommentSerializer
from blog.models import BlogPost, Comment


@api_view(['GET'],)
@authentication_classes([])
@permission_classes([])
def all_blog_posts(request):
    blog = BlogPost.objects.all()
    serializer = BlogPostSerializer(blog, many=True)
    context = {
        'post': serializer.data
    }
    return Response(context)


@api_view(['GET'],)
@authentication_classes([])
@permission_classes([])
def view_blog(request, uuid):
    blog = BlogPost.objects.get(uuid=uuid)
    serializer = BlogPostSerializer(blog)
    comments = blog.comment_set.all()
    comment_serializer = CommentSerializer(comments, many=True)
    context = {
        'post': serializer.data,
        'comments': comment_serializer.data
    }
    return Response(context)

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import BlogPost, Comment
from .forms import CommentForm, BlogPostForm
from account.decorators import allowed_roles


def blog(request):
    recent_posts = BlogPost.objects.all().order_by('-posted_on')[:10]
    context = {'recent_posts': recent_posts}
    return render(request, 'blog/index.html', context)


@login_required(login_url='login')
@allowed_roles(roles=['admin', 'subadmin'])
def create_blog(request):
    form = BlogPostForm()
    if request.method == 'POST':
        form = BlogPostForm(request.POST, request.FILES)
        if form.is_valid():
            b = form.save(commit=False)
            b.posted_by = request.user
            b.save()
            return redirect('a_blog')
    context = {'form': form}
    return render(request, 'blog/create_blog.html', context)


@login_required(login_url='login')
@allowed_roles(roles=['admin', 'subadmin'])
def edit_blog(request, uuid):
    blog_post = BlogPost.objects.get(uuid=uuid)
    form = BlogPostForm(instance=blog_post)

    if request.method == 'POST':
        form = BlogPostForm(request.POST, request.FILES, instance=blog_post)
        if form.is_valid():
            form.save()
            return redirect('a_blog')
    context = {'form': form, 'edit': True}
    return render(request, 'blog/create_blog.html', context)


@login_required(login_url='login')
@allowed_roles(roles=['admin', 'subadmin'])
def delete_blog(request, uuid):
    b_post = BlogPost.objects.get(uuid=uuid)
    b_post.delete()
    return redirect('a_blog')


def details(request, uuid):
    blog_post = BlogPost.objects.get(uuid=uuid)
    others = BlogPost.objects.exclude(uuid=uuid).order_by('-posted_on')[:5]
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = blog_post
            comment.posted_by = request.user
            comment.save()
    context = {'blog': blog_post, 'form': form, 'others': others}
    return render(request, 'blog/details.html', context)


@login_required(login_url='login')
@allowed_roles(roles=['admin', 'user', 'subadmin'])
def edit_comment(request, pk):
    comment = Comment.objects.get(id=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
    return redirect('blog_post', comment.post.uuid)


@login_required(login_url='login')
@allowed_roles(roles=['admin', 'user', 'subadmin'])
def delete_comment(request, pk):
    comment = Comment.objects.get(id=pk)
    comment.delete()
    return redirect('blog_post', comment.post.uuid)

administration/templates/administration/case_details.html
{% extends 'administration/admin_base.html' %}
{% block content %}
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
              <li class="breadcrumb-item"><a href="#">Cases</a></li>
              <li class="breadcrumb-item"><a href="#">{{case.title}}</a></li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid mt--6">
  <div class="row">
    <div class="{% if case.status == 'Green' %} col-xl-8 {% else %} col-xl-12 {% endif %}">
      <div class="card">
        <div class="card-header">
          <div class="row align-items-center">
            <div class="col-6">
              <h3 class="mb-0">Case Details </h3>
            </div>
            <div class="col-6">
              {% if case.status != 'Green' and case.status != 'Closed' %}
                <a href="{% url 'a_approve' case.uuid %}" class="btn btn-sm btn-success">Approve</a>
              {% endif %}
              <a href="{% url 'a_edit' case.uuid %}" class="btn btn-sm btn-primary">Edit Case</a>
              <a href="{% url 'a_close' case.uuid %}" class="btn btn-sm btn-default">Close Case</a>
              {% if request.user.get_group != 'subadmin' %}
              <a href="{% url 'a_delete' case.uuid %}" class="btn btn-sm btn-danger">Delete</a>
              {% endif %}
              {% if case.status == 'Orange' %}
                <a href="{% url 'a_reject' case.uuid %}" class="btn btn-sm btn-danger">Reject Case</a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="container mb-4" style="width: 70%;">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
              <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                {% for d in case.extraimages_set.all %}
                <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter1 }}"></li>
                {% endfor %}
              </ol>
              <div class="carousel-inner">
                {% if case.thumbnail %}
                <div class="carousel-item active">
                  <img src="{{ case.thumbnail.url }}" class="img-fluid">
                </div>
                {% endif %}
                {% for d in case.extraimages_set.all %}
                  <div class="carousel-item">
                    <img class="img-fluid" src="{{d.img.url}}">
                  </div>
                {% endfor %}
              </div>
              <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
          {% for m in messages %}
          <div class="alert alert-default" role="alert">
            {{m}}
          </div>
          {% endfor %}

          <h4 class="info-title text-uppercase text-primary">{{case.title}}</h4>
          <span class="badge badge-secondary badge-pill mb-3 text-white">{{case.type}}</span>

          <span class="
             badge {% if case.status == 'Green' %} badge-success
             {% elif case.status == 'Orange' %} badge-warning
             {% elif case.status == 'Red' %} badge-danger
             {% elif case.status == 'Closed' %} badge-default {% endif %}
             badge-pill mb-3">
            {{case.status}}
          </span>

          <p class="description display-4">
            {{case.description|safe}}
          </p>
          <p class="paragraph">Created By: <a href="#">{{case.created_by.user}}</a></p>
          {% if case.type == 'Medical' %}
            <ul>
              <li>Nature Of Disease: {{case.medicalcase.nature_of_disease}}</li>
              <li>Hospital: {{case.medicalcase.name_of_hospital}}</li>
              <li>Admitted: {{case.medicalcase.admitted_in_hospital}}</li>
            </ul>
            <p class="description display-1">Files : </p>

            <ul>
              <li>Estimation Letter:
                {% if case.medicalcase.estimation_letter %}
                  <a href="{{MEDIA_URL}}{{case.medicalcase.estimation_letter.url }}">{{case.medicalcase.estimation_letter}}</a>
                {% else %}
                  <b>This File Was Not Provided</b>
                {% endif %}
              </li>
            </ul>

          {% elif case.type == 'Medicine' %}
            <ul>
              <li>Nature Of Disease: {{case.medicinecase.nature_of_disease}}</li>
              <li>Medicine: {{case.medicinecase.name_of_medicine}}</li>
              <li>Hospital: {{case.medicinecase.name_of_hospital}}</li>
            </ul>
            <p class="description display-1">Files : </p>

            <ul>
              <li>Estimation Letter:
                {% if case.medicinecase.estimation_letter %}
                  <a href="{{MEDIA_URL}}{{case.medicinecase.estimation_letter.url }}">{{case.medicinecase.estimation_letter}}</a>
                {% else %}
                  <b>This File Was Not Provided</b>
                {% endif %}
              </li>
            </ul>

          {% elif case.type == 'Provisional' %}
            <ul>
              <li>Marital Status: {{case.provisionalcase.marital_status}}</li>
            </ul>

            {% if case.provisionalcase.marital_status == 'Widow' %}
              <p class="description display-1">Files :</p>

              <ul>
                <li>Death Certificate: <a href="{{MEDIA_URL}}{{case.provisionalcase.death_cert.url }}">{{case.provisionalcase.death_cert}}</a></li>
              </ul>
            {% endif %}

          {% elif case.type == 'Educational' %}
            <ul>
              <li>Is an orphan: {{case.educationalcase.is_orphan}}</li>
              <li>Father/Mother/Guardian: {{case.educationalcase.guardian}}</li>
              <li>Name of school: {{case.educationalcase.name_of_school}}</li>
              <li>Location of school: {{case.educationalcase.location_of_school}}</li>
              <li>Grade: {{case.educationalcase.grade}}</li>
            </ul>

            <p class="description display-1">Files : </p>

            <ul>
              {% if case.educationalcase.is_orphan %}
              <li>Death Certificate:
                {% if case.educationalcase.death_cert %}
                  <a href="{{MEDIA_URL}}{{case.educationalcase.death_cert.url }}">{{case.educationalcase.death_cert}}</a>
                {% else %}
                  <b>File was not provided</b>
                {% endif %}
              </li>
              {% endif %}
              <li>Fee Structure:
                {% if case.educationalcase.fee_structure %}
                <a href="{{MEDIA_URL}}{{case.educationalcase.fee_structure.url }}">{{case.educationalcase.fee_structure}}</a>
                {% else %}
                <b>File was not provided</b>
                {% endif %}
              </li>
            </ul>


          {% else %}
            <ul>
              <li>Nature Of Aid: {{case.generalcase.nature_of_aid}}</li>
            </ul>
            <p class="description display-1">Files : </p>

            <ul>
              <li>Estimated Cost Certificate:
                {% if case.generalcase.estimated_cost_cert %}
                  <a href="{{MEDIA_URL}}{{case.generalcase.estimated_cost_cert.url }}">{{case.generalcase.estimated_cost_cert}}</a>
                {% else %}
                  <b>This file was not provided</b>
                {% endif %}
              </li>
            </ul>
          {% endif %}

            <p class="description display-4">
              Submitted on: {{case.date_of_initiation.date}}
            </p>
            <p class="description display-3">
              Financial Assistance From Other Sources: {{case.other_financial_assistance}}
            </p>

            {% if case.status == 'Closed' %}
            <h2 class="display-4">Closing Documents</h2>
            <ul>
              {% for d in case.closeddocs_set.all %}
                <li><a href="{{MEDIA_URL}}{{d.doc.url }}">{{d.doc}}</a></li>
              {% endfor %}
            </ul>
            <hr>
            <form role="form" method="POST" action="{% url 'a_close' case.uuid %}" enctype="multipart/form-data">
              {% csrf_token %}
                <div class="form-group mb-3">
                    <label class="form-control-label">Add New Closing Documents</label>
                    <div class="input-group input-group-merge input-group-alternative">
                        <input type="file" class="form-control" name="c_docs" multiple>
                    </div>
                </div>
                <div class="text-center">
                    <input type="submit" class="btn btn-primary my-4" value="Add New Documents">
                </div>
            </form>
          {% endif %}
          <h2 class="display-5">Extra Documents</h2>
          <ul>
            {% for d in case.extradocs_set.all %}
              <li><a href="{{MEDIA_URL}}{{d.doc.url }}">{{d.doc}}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
    {% if case.status == 'Green' %}
    <div class="col-xl-4">
        <div class="card">
        <div class="card-header">
          <div class="row align-items-center">
            <div class="col-8">
              <h3 class="mb-0">Case Progress </h3>
            </div>
          </div>
        </div>
        <div class="card-body">

            <div class="progress-wrapper">
                <div class="progress-info">
                  <div class="progress-label">
                    <h3>Raised <b>&#8377;{{case.proper_total}}</b> of <b>&#8377;{{case.requested_amount}}</b></h3>
                  </div>
                  <div class="progress-percentage">
                    <span>{{ progress|floatformat:2 }}%</span>
                  </div>
                </div>
                <div class="progress">
                  <div class="progress-bar bg-primary"
                       role="progressbar" aria-valuenow="{{case.total_collected}}"
                       aria-valuemin="0" aria-valuemax="{{case.requested_amount}}" style="width: {{progress}}%"></div>
                </div>
              </div>
            </div>
        </div>
    </div>
    {% endif %}

  </div>
{% if case.status == 'Green' %}
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header border-0">
              <div class="row align-items-center">
                <div class="col">
                  <h3 class="mb-0">Donations Received</h3>
                </div>
              </div>
            </div>
            <div class="table-responsive">
              <!-- Projects table -->
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">Donor</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Date</th>
                  </tr>
                </thead>
                <tbody>
                {% for donation in donations %}
                  <tr>
                    <th scope="row">
                      {{donation.donor}}
                    </th>
                    <td>
                      {{donation.amount}}
                    </td>
                    <td>
                      {{donation.date.date}}
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
    </div>
  </div>
  {% endif %}
{% endblock %}